import { Abril_Fatface, Arbutus_Slab, Bodoni_Moda, Oswald, Peddana, Poiret_One } from 'next/font/google';
import "./globals.css";

const abrilFatface = Abril_Fatface({
  subsets: ['latin'],
  weight: '400',  // Abril Fatface only has one weight
  variable: '--font-abril-fatface',
});

const arbutusSlab = Arbutus_Slab({
  subsets: ['latin'],
  weight: '400',  // Arbutus Slab also has single weight
  variable: '--font-arbutus-slab',
});

const bodoniModa = Bodoni_Moda({
  subsets: ['latin'],
  weight: '400',  // You can pick weight like '400', '500', etc.
  variable: '--font-bodoni-moda',
});

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['200'],  // You asked for weight 200
  variable: '--font-oswald',
});

const peddana = Peddana({
  subsets: ['latin'],
  weight: '400', // Default
  variable: '--font-peddana',
});

const poiretOne = Poiret_One({
  subsets: ['latin'],
  weight: '400', // Only one weight
  variable: '--font-poiret-one',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={`${abrilFatface.variable} ${arbutusSlab.variable} ${bodoniModa.variable} ${oswald.variable} ${peddana.variable} ${poiretOne.variable}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
